spring:
  application:
    name: confcenterserver
  redis:
    single: 192.168.183.9:6378
    cluster:
      nodes: 192.168.183.9:6378
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: 3000
    timeout: 3000
    password:
  thymeleaf:
    cache: false
#    mode: LEGACYHTML5

confserver:
  confs:
    basepath: D:\my_study\study_java\IConfCenter\ConfCenterServer\ConfCenter\confserver\src\main\resources\confs #配置中心上传配置文件存储路径
    currentConfVersion: application-20180903.properties #默认需要同步配置的版本

server:
  port: 8000